/* Content for the portfolio UI kit. Copy is verbatim from the CONTENT object
   in the source repo (src/App.jsx). Image keys that point at a generated SVG
   plate upstream are rendered here as flat placeholder boxes — see README.md. */
window.PortfolioData = {
  meta: { name: 'Manel López', monogram: 'M', role: 'Senior Product Designer', location: 'Barcelona, Spain' },
  links: {
    email: 'manellopez.alu@gmail.com',
    linkedin: 'https://www.linkedin.com/in/manel-lf/',
    behance: 'https://www.behance.net/manellpez',
    bookACall: 'https://cal.com/manel-lopez-wc3pop/book-a-call',
  },
  hero: {
    name: 'Manel López',
    roles: ['Product Designer', 'Engineer', 'Systems Designer', 'AI Prototyper', 'Gamificator', 'Product Thinker', 'University Lecturer', 'Cat Butler'],
    bio: 'From research and analytics to prototypes and production, I help turn ideas into products people return to.',
    scrollHint: 'Scroll',
  },
  booking: {
    title: 'Book a call',
    subtitle: 'Pick a slot that suits you — 30 minutes, no agenda needed.',
    newTabLabel: 'Open in a new tab instead',
    loadingLabel: 'Loading available times…',
  },
  logos: {
    label: 'Companies and teams I have designed for',
    perPage: 5,
    intervalMs: 4000,
    fadeMs: 960,
    items: [
      { name: 'GameHouse', logo: 'gamehouse.svg', aspect: 8.201, scale: 0.62 },
      { name: 'Jesterday', logo: 'jesterday.svg', aspect: 3.292, scale: 1.45 },
      { name: 'Eunoia Digital', logo: 'eunoiadigital.svg', aspect: 12.264, scale: 0.45 },
      { name: 'Popcore Games', logo: 'popcore.svg', aspect: 6.036, scale: 0.9 },
      { name: 'SEAT CUPRA', logo: 'cupra.svg', aspect: 7.008, scale: 0.85 },
      { name: 'Socialpoint', logo: 'socialpoint.svg', aspect: 4.867 },
      { name: 'La Salle BCN', logo: 'lasalle.svg', aspect: 3.526, scale: 1.4 },
      { name: 'Kave Home', logo: 'kavehome.svg', aspect: 5.581, scale: 0.95 },
      { name: 'MURIS', logo: 'murisbrand.svg', aspect: 4.68 },
      { name: 'Radisson Hotels', logo: 'radisson.svg', aspect: 2.681, scale: 1.5 },
    ],
  },
  work: { eyebrow: 'Recent work.', heading: 'From pixels to products.', spotlightSlug: 'gamehouse-plus' },
  bits: {
    eyebrow: 'Design bits.',
    heading: 'What I have lately been working on.',
    rowLabels: ['Prototypes and tooling', 'Systems and analysis'],
    items: [
      { id: 'bit-claude-figma', kicker: 'AI tooling', caption: 'A working prototype in an afternoon — Claude Code driving the build, the Figma MCP keeping it on the design system.', image: 'journal-tcebc-tool.jpg' },
      { id: 'bit-energy', kicker: 'Game economy', caption: 'Jesterday’s energy economy modelled in a spreadsheet and tuned against session length before a single screen was drawn.' },
      { id: 'bit-teaching', kicker: 'Teaching', caption: 'Research-methods material for a UX course inside an AI and Data Science degree at La Salle URL.' },
      { id: 'bit-instant', kicker: 'Prototype', caption: 'Five entry-point variants for instant play, narrowed to one by putting a real build in front of players.', image: 'scavenger-hunt-thumbnail.jpg' },
      { id: 'bit-tokens', kicker: 'Design systems', caption: 'Design tokens as the contract between Figma and Unity, so a colour change is one commit rather than a meeting.' },
      { id: 'bit-typeramp', kicker: 'Automotive', caption: 'One type ramp that has to stay legible from a 7-inch cluster to a 15-inch centre display, at arm’s length, in sunlight.' },
      { id: 'bit-analytics', kicker: 'Product analytics', caption: 'The funnel that told me a feature I had already shipped was solving the wrong half of the problem.' },
      { id: 'bit-componentapi', kicker: 'Craft', caption: 'Sketching the component API before the component — props first, pixels second.' },
    ],
  },
  about: {
    eyebrow: 'About me.',
    heading: 'Design that ships.',
    title: 'AI Native Designer. Design Thinker.',
    body: [
      'I came to design through engineering. The degree gave me the systems habit — read the constraints, model the thing, then draw it — and a Master’s in User Experience gave me the research and evaluation side to go with it.',
      'Today I own a consumer subscription app end to end at GameHouse, and I teach UX inside an AI and Data Science degree at La Salle URL. Teaching keeps the fundamentals sharp; the engineering background means I can build the prototype instead of describing it.',
    ],
  },
  testimonials: {
    eyebrow: 'Shoutouts.',
    heading: 'What stakeholders and teammates say about me.',
    intro: 'People I have worked with directly, across product, design and engineering. Happy to put you in touch with any of them.',
    quotes: [
      { id: 'q-emmi', quote: 'Manel combines strong design skills with genuine product thinking. He consistently keeps the user at the center, runs usability tests, and uses feedback to improve. He embraces feedback while confidently challenging perspectives with thoughtful reasoning and a clear point of view. He has a strong sense of product vision and translates it into coherent, consistent experiences.', name: 'Emmi Kuusikko', role: 'Head of Product', avatar: 'testimonial-emmi-kuusikko.jpg', href: 'https://www.linkedin.com/in/emmik/' },
      { id: 'q-lea', quote: 'Manel consistently acted above his level as a Senior UI/UX Designer. He presented ideas in front of senior management and defended them with confidence. He combines UI/UX craft excellence with strong prototyping and technical skills, paired with sharp abstraction and communication skills, which is a rare mix. Whoever gets to work with Manel will be very lucky.', name: 'Lea Schönfelder', role: 'UX Creative Director', avatar: 'testimonial-lea-schonfelder.jpg', href: 'https://www.linkedin.com/in/lea-schoenfelder/' },
      { id: 'q-alex', quote: 'Manel consistently delivers clean and visually appealing designs. He’s great at bringing Product and Development together, making sure everyone is aligned and ideas move smoothly from concept to delivery. Even with tight deadlines, he stays collaborative, open to new ideas, and focused on finding practical solutions.', name: 'Alex Segura', role: 'Frontend Developer', avatar: 'testimonial-alex-segura.jpg', href: 'https://www.linkedin.com/in/xlerida/' },
    ],
  },
  journal: {
    eyebrow: 'Journal.',
    heading: 'Notes from the work.',
    posts: [
      {
        slug: 'grounding-ideas-fast', date: 'June 2026', tags: ['Process', 'Prototyping'], readMins: 6,
        title: 'Grounding ideas fast is changing how I design',
        dek: 'The distance between a question and an answer used to be a chain of documents. Collapsing it changed what design review is even about.',
        image: 'journal-tcebc-tool.jpg',
        body: [
          { p: 'For most of my career, the distance between “what if we tried this” and an actual answer was measured in days. Wireframe, then flow, then mockup, then a slow march toward something you could put in front of a person. Somewhere in that chain the original question quietly got answered by the effort of building the deck meant to answer it, rather than by anything resembling evidence.' },
          { h: 'The old shape of the process' },
          { p: 'The linear version goes: ideation, wireframes, flows, low-fidelity mockups, prototyping, and eventually a Figma prototype that is convincing from the front and hollow behind. Each step is a translation of the step before it, and every translation is a place to quietly lose the thing that mattered about the original idea.' },
          { figure: 'The old shape: a chain of translations between the question and an answer.' },
          { h: 'What actually changed in the room' },
          { p: 'The practical shift is not speed for its own sake, it is where judgment gets spent. I used to defend a direction that had not been tested yet — taste standing in for evidence, because evidence was a week away. Now I bring the thing, and the room reacts to the thing. Design review has moved from arguing about opinions to reading a result that already exists.' },
          { stats: [{ value: 'Same day', label: 'Idea to a testable build' }, { value: 'Fewer', label: 'Slide decks defending a hunch' }, { value: 'Earlier', label: 'Point where reality gets a vote' }] },
          { h: 'Where I still do it the old way' },
          { p: 'Framing, research, and the call about what is actually worth building — that work did not get any cheaper, and I do not let it. A tighter loop compresses the distance between a defined idea and a working answer. It does not decide which idea deserves the trip.' },
        ],
        references: [
          { label: "A designer's framework for better AI prompts — Figma Blog", href: 'https://www.figma.com/blog/designer-framework-for-better-ai-prompts/' },
        ],
      },
      { slug: 'claude-code-toolkit', date: 'June 2026', tags: ['Prototyping', 'AI Tooling'], readMins: 6, title: 'My toolkit for prototyping with Claude Code', dek: 'The setup behind a working prototype: one terminal and a small, swappable stack of MCPs and skills layered on top of it.' },
      { slug: 'framework-to-agent', date: 'May 2026', tags: ['AI Tooling', 'Process'], readMins: 5, title: 'From a prompt framework to an agent that writes them', dek: 'A fixed framework got the prompts good enough to keep. Handing the framework itself to an agent got them better.' },
    ],
  },
  contact: {
    eyebrow: 'Get in touch.',
    heading: 'Let’s talk.',
    intro: 'Open to senior product design roles, design system work, and prototyping engagements with product and games teams. Also available for guest lectures and workshops.',
    emailLabel: 'Or email me directly',
    fields: {
      name: { label: 'Your name', placeholder: 'Hiring Manager' },
      email: { label: 'Your email', placeholder: 'you@company.com' },
      subject: { label: 'Subject', placeholder: 'Senior Product Designer role' },
      message: { label: 'Message', placeholder: 'A line or two about the team, the product and the problem.' },
    },
    submitLabel: 'Send message',
    submittingLabel: 'Sending…',
    sentTitle: 'Message sent.',
    sentBody: 'Thanks — it landed in my inbox and I’ll come back to you shortly.',
    resetLabel: 'Write another',
    errors: {
      name: 'Please tell me your name.',
      email: 'Please enter a valid email address.',
      subject: 'Please add a subject.',
      message: 'Please add a message — a couple of sentences is plenty.',
    },
  },
  footer: {
    rail: [
      { id: 'work', label: 'Work' }, { id: 'bits', label: 'Bits' }, { id: 'about', label: 'About' },
      { id: 'shoutouts', label: 'Shoutouts' }, { id: 'journal', label: 'Journal' }, { id: 'contact', label: 'Contact' },
    ],
    railLabel: 'Sections on this page',
    copyright: '© 2026 Manel López',
    madeIn: 'Designed and built in Barcelona.',
  },
  caseUi: {
    eyebrow: 'End-to-End Design',
    titlePrefix: 'For',
    backLabel: 'Back to work',
    metaLabels: { role: 'Role', years: 'Years', skills: 'Skills' },
    rail: [
      { id: 'overview', label: 'Overview' }, { id: 'process', label: 'Process' },
      { id: 'system', label: 'System' }, { id: 'extend', label: 'Extend' }, { id: 'impact', label: 'Impact' },
    ],
    railLabel: 'Sections in this case study',
  },
  projects: [
    {
      slug: 'gamehouse-plus',
      name: 'GameHouse+', eyebrow: 'GameHouse+',
      spotlightLogo: 'ghplus-colored.svg', spotlightLogoAspect: 4.457,
      spotlightTitle: ['Rethinking how players start playing.', 'A product-wide pivot to in-app games.'],
      positioning: 'A consumer subscription app for casual games, repositioned around instant play.',
      cardDescription: 'End-to-end ownership of a casual-games subscription app — research, product analytics, design system and the first-session rebuild.',
      role: 'Senior Product Designer — end-to-end ownership',
      years: '2023 — Present',
      skills: ['UX Design', 'UX Research', 'Product Analytics', 'Design Systems', 'Prototyping', 'Visual'],
      metrics: [{ value: '6×', label: 'Day-0 activation' }, { value: '6×', label: 'Faster time to first session' }, { value: '2×', label: 'Day-1 retention' }],
      heroImage: 'scavenger-hunt-thumbnail.jpg',
      overview: {
        eyebrow: 'Overview:', heading: 'Backstory of the work.',
        body: [
          'GameHouse+ is a subscription app for casual games. I own it end to end — discovery, research, interaction design, the design system, the visual language, and the analytics that tell us whether any of it worked.',
          'The product had a catalogue people liked and a first session almost nobody finished. Installs arrived, the store loaded, and the majority of new users left before they had played anything at all. The subscription was being asked to justify itself before it had delivered a single minute of value.',
        ],
      },
      process: {
        eyebrow: 'Process:', heading: 'How I kicked things off.',
        body: [
          'I started where the disagreement was: everyone had a theory about why activation was low, and none of them were written down. So I made the current state undeniable before proposing anything.',
          'Session recordings and funnel analysis first, then a short round of moderated sessions with new users, then a written problem statement the whole team could argue with. Only after that did I start drawing.',
        ],
        cards: [
          { title: 'Funnel teardown', meta: 'Product analytics', body: 'Instrumented the first session step by step in Amplitude and found the drop was not at paywall or signup — it was in the gap between opening the app and anything being playable.' },
          { title: 'Moderated first sessions', meta: 'UX research', body: 'Watched new users open the app cold. The catalogue read as a decision to make rather than an invitation to play, and the download wait broke the moment of intent.' },
          { title: 'Problem statement', meta: 'Framing document', body: 'One page: what we observed, what it costs, what we are choosing to optimise, and what we are explicitly not solving in this cycle. Signed off by product and engineering before design started.' },
          { title: 'Instant-play hypothesis', meta: 'Concept', body: 'If the first thing a new user meets is content already running rather than a catalogue to browse, activation stops depending on a download completing.' },
          { title: 'Coded prototype', meta: 'Prototyping', body: 'Built the entry flow as a working prototype rather than a clickable mock, so latency, loading and failure states were real and could be tested honestly.' },
          { title: 'Instrumented rollout', meta: 'Validation', body: 'Shipped behind a flag with the funnel already wired, so the comparison against the old first session was available in days rather than after a quarter.' },
        ],
      },
      system: {
        eyebrow: 'Shaping the system:', heading: 'Shaping the system for GameHouse+.',
        body: [
          'The pivot only holds if the surfaces around it are consistent, so I built the design system in parallel with the flow rather than after it. Tokens for colour, type, spacing and motion; a component library with real states rather than happy-path artwork; and documented rules for how content density behaves as the catalogue grows.',
          'The system is deliberately small. Every component in it exists because two or more surfaces needed it, and each one ships with its loading, empty, error and offline states — those are the states a games subscription actually spends its time in.',
        ],
      },
      extend: {
        eyebrow: 'Extend:', heading: 'Store and marketing surfaces.',
        body: [
          'Once the in-app language settled, the same system had to carry the surfaces that sit outside the app: store listings, lifecycle email, acquisition landing pages and the in-app merchandising slots that promote new content.',
          'Reusing the tokens and components meant the promise made in an ad matched the first screen a new user saw. That continuity is a measurable part of activation, not a brand nicety.',
        ],
      },
      impact: {
        eyebrow: 'The impact:', heading: 'Activation, and what changed.',
        body: [
          'The instant-content pivot delivered six times day-0 activation, a six-fold reduction in time to first session, and double day-1 retention. The first session stopped being a decision and became an experience.',
          'The more durable change is how the team now works. A problem statement precedes design, prototypes are functional before they are pretty, and the funnel is instrumented before a feature ships rather than after someone asks how it is doing. I have since used the same analytics to argue for redirecting a feature I had already shipped myself.',
        ],
      },
    },
    {
      slug: 'jesterday', name: 'Jesterday', eyebrow: 'GPixel · Jesterday',
      logo: 'jesterday.svg', logoAspect: 3.292,
      thumbnail: 'jesterday-thumbnail.svg',
      externalUrl: 'https://www.behance.net/gallery/215857737/GPixel-Arcade-Racing-Mobile-Game-UXUI-Design-Case',
      positioning: 'An indie mobile multiplayer title, given a design system and an economy that survive production.',
      cardDescription: 'Indie mobile multiplayer. Design system built from scratch, an energy economy modelled end to end, and the component library implemented in Unity.',
      role: 'Product Designer & Design System Owner', years: '2022 — 2023',
    },
    {
      slug: 'seat-cupra', name: 'SEAT CUPRA', eyebrow: 'SEAT CUPRA',
      logo: 'cupra.svg', logoAspect: 7.008, logoScale: 0.85,
      positioning: 'In-car infotainment for connected services — enrolment, data plans and software updates, across every screen in the range.',
      cardDescription: 'In-car infotainment. Connected-services enrolment, data plan purchase and an update centre, designed to hold from 7-inch clusters to 15-inch displays.',
      role: 'Product Designer, Connected Services', years: '2021 — 2022',
    },
    {
      slug: 'radisson', name: 'Radisson Hotels', eyebrow: 'Radisson Hotels — via Eunoia Digital',
      logo: 'radisson.svg', logoAspect: 2.681, logoScale: 1.5,
      positioning: 'Enterprise interfaces, flows and UI kits for a global hotel group, produced at agency scale.',
      cardDescription: 'Enterprise interfaces for a global hotel group. Flows, screens and reusable UI kits delivered at agency pace without losing consistency.',
      role: 'Product Designer, Eunoia Digital', years: '2020 — 2021',
    },
    {
      slug: 'scavenger-hunt', name: 'Scavenger Hunt', eyebrow: 'Scavenger Hunt · Popcore',
      logo: 'popcore.svg', logoAspect: 6.036,
      thumbnail: 'scavenger-hunt-thumbnail.jpg',
      externalUrl: 'https://www.behance.net/gallery/194452315/Scavenger-Hunt-Hyper-Casual-Mobile-Game-UXUI-Design',
      positioning: 'Live-events design support on a top-grossing mobile title.',
      cardDescription: 'Live events on a top-grossing mobile game. Designing a recurring event so it reads instantly, ships on cadence and never blocks the release train.',
      role: 'Product Designer, Live Events', years: '2023',
    },
  ],
};
